//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AASTHA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosis_master
    {
        public int digagnosis_typeId { get; set; }
        public string diagnosis_type { get; set; }
    }
}
