//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AASTHA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_medicine_type
    {
        public tbl_medicine_type()
        {
            this.medicine_master = new HashSet<medicine_master>();
            this.medicine_master1 = new HashSet<medicine_master>();
        }
    
        public int medicine_Id { get; set; }
        public string medicine_type { get; set; }
    
        public virtual ICollection<medicine_master> medicine_master { get; set; }
        public virtual ICollection<medicine_master> medicine_master1 { get; set; }
    }
}
