//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AASTHA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_delivery
    {
        public int delivery_Id { get; set; }
        public Nullable<int> Ipd_Id { get; set; }
        public string delivery_typeId { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<System.TimeSpan> delivery_time { get; set; }
        public string baby_gender { get; set; }
        public Nullable<decimal> baby_weight { get; set; }
        public string diagnosis { get; set; }
    
        public virtual tbl_Ipd tbl_Ipd { get; set; }
    }
}
