//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AASTHA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ipd
    {
        public tbl_Ipd()
        {
            this.IPD_Charge_Details = new HashSet<IPD_Charge_Details>();
            this.tbl_delivery = new HashSet<tbl_delivery>();
            this.tbl_general = new HashSet<tbl_general>();
            this.tbl_operation = new HashSet<tbl_operation>();
        }
    
        public int ipd_Id { get; set; }
        public string ipd_receipt_id { get; set; }
        public string dept_name { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string room_type { get; set; }
        public Nullable<System.DateTime> addmission_date { get; set; }
        public Nullable<System.DateTime> discharge_date { get; set; }
        public Nullable<decimal> bill { get; set; }
        public Nullable<decimal> conssesion { get; set; }
    
        public virtual ICollection<IPD_Charge_Details> IPD_Charge_Details { get; set; }
        public virtual ICollection<tbl_delivery> tbl_delivery { get; set; }
        public virtual ICollection<tbl_general> tbl_general { get; set; }
        public virtual tbl_patient tbl_patient { get; set; }
        public virtual ICollection<tbl_operation> tbl_operation { get; set; }
    }
}
